;;; Scheme Recursive Art Contest Entry
;;;
;;; Please do not include your name or personal info in this file.
;;;
;;; Title: B L M .
;;;
;;; Description:
;;;   <Black lives, they matter.
;;;    Centuries of injustice,
;;;    Now, it's up to us.>

(define (draw)
  ; YOUR CODE HERE
  (define (draw-b size)
    (begin_fill)
    (pendown)
    (forward size)
    (right 90)
    (forward (/ size 3))
    (right 180)
    (circle (/ size 4) -180)
    (right 180)
    (circle (/ size 4) -180)
    (right 180)
    (forward (/ size 3))
    (end_fill))
  (define (go-to-next size)
    (penup)
    (define new-size (/ (* 8 size) 12))
    (backward new-size)
    (right 90))
  (define (draw-l size)
    (begin_fill)
    (pendown)
    (define new-size (/ (* 7 size) 12))
    (forward size)
    (right 90)
    (forward (/ new-size 3))
    (right 90)
    (forward (- size (/ new-size 3)))
    (left 90)
    (forward (/ (* 2 new-size) 3))
    (right 90)
    (forward (/ new-size 3))
    (right 90)
    (forward new-size)
    (end_fill))
  (define (draw-m size)
    (begin_fill)
    (pendown)
    (define new-size (/ size 12))
    (forward size)
    (right 90)
    (forward (* new-size 2.625))
    (right 68)
    (forward (* new-size 9.25845))
    (left 136)
    (forward (* new-size 9.25845))
    (right 68)
    (forward (* new-size 2.625))
    (right 90)
    (forward size)
    (right 90)
    (forward (* new-size 1.75))
    (right 90)
    (forward (* new-size 8.5715))
    (left 158)
    (forward (* new-size 9.42375))
    (right 68)
    (forward (* new-size 1.75))
    (right 68)
    (forward (* new-size 9.42375))
    (left 158)
    (forward (* new-size 8.5715))
    (right 90)
    (forward (* new-size 1.75))
    (end_fill))
  (define (draw-period size)
    (forward (/ size 9))
    (begin_fill)
    (pendown)
    (circle (/ size 8))
    (end_fill))
  (define (draw-blm size x y)
    (penup)
    (setposition x y)
    (draw-b size)
    (go-to-next size)
    (draw-l size)
    (go-to-next size)
    (draw-m size)
    (go-to-next (* 2 size))
    (draw-period size))
  (define (draw-fist size c x y)
    (penup)
    (setposition x y)
    (color c)
    (pendown)
    (begin_fill)
    (right 8)
    (forward (* 6.4 size))
    (left 42)
    (forward (* 7.4 size))
    (right 72)
    (forward (* 9.1 size))
    (right 96)
    (forward (* 10.7 size))
    (right 71)
    (forward (* 7.3 size))
    (left 25)
    (forward (* 5.6 size))
    (right 90)
    (forward size)
    (end_fill)
    (draw-fist-inside size x y))
  (define (draw-fist-inside size x y)
    (penup)
    (color "white")
    (setposition x y)
    (right 98)
    (forward (* 6.4 size))
    (left 42)
    (forward (* 7.4 size))
    (right 72)
    (forward (* 5.6 size))
    (pendown)
    (right 76)
    (forward (* 2.8 size))
    (left 84)
    (forward (* 2.6 size))
    (backward (* 2.6 size))
    (right 84)
    (forward (* 1.8 size))
    (right 61)
    (forward (* 2.2 size))
    (right 77)
    (forward (* 2.9 size))
    (right 62)
    (forward (* 1.8 size))
    (backward (* 1.6 size))
    (left 114)
    (forward (* 0.4 size))
    (left 99)
    (forward (* 2.8 size))
    (left 73)
    (forward (* 5.2 size))
    (backward (* 5.2 size))
    (right 73)
    (forward (* 2.5 size))
    (left 69)
    (forward (* 4.2 size))
    (backward (* 4.2 size))
    (right 93)
    (forward (* 2 size))
    (left 85)
    (forward (* 1.5 size))
    (left 40))
  (define (fists size)
    (draw-fist (/ size 36) "#ffdbac" -500 -500)
    (draw-fist (/ size 32) "#f1c27d" -420 -500)
    (draw-fist (/ size 28) "#e0ac69" -340 -500)
    (draw-fist (/ size 24) "#c68642" -260 -500)
    (draw-fist (/ size 20) "#8d5524" -180 -500)
    (draw-fist (/ size 36) "#ffdbac" 400 -500)
    (draw-fist (/ size 32) "#f1c27d" 305 -500)
    (draw-fist (/ size 28) "#e0ac69" 210 -500)
    (draw-fist (/ size 24) "#c68642" 115 -500)
    (draw-fist (/ size 20) "#8d5524" 20 -500))
  (define (do-all size)
    (hideturtle)
    (draw-blm (/ size 1.5) -425 150)
    (fists size)
    (draw-fist (/ size 16) "black" -100 -500))
  (do-all 500)
  (exitonclick))

; Please leave this last line alone.  You may add additional procedures above
; this line.
(draw)
