;;; Scheme Recursive Art Contest Entry
;;;
;;; Please do not include your name or personal info in this file.
;;;
;;; Title: <Python Ok?>
;;;
;;; Description:
;;;   <We python ok,
;;;    but when does python ask
;;;    if we are ok?
(define (heart)
    (penup)
    (backward 100)
    (right 90)
    (pendown)
    (color "red")
    (left 140)
    (forward 180)
    (circle -90 200)
    (left 120)
    (circle -90 200)
    (forward 180)
)
(define (heart-maker n)
  (if(= n 1) (begin (heart) (penup)) (begin (heart) (backward 200) (heart-maker (- n 1))))

)
(define (eye)
  (pendown)
  (color "black")
  (begin_fill)
  (circle 24 360)
  (color "white")
  (end_fill)
  (penup)
)
(define (tear n)
  (forward 15)
  (pendown)
  (begin_fill)
  (color "blue")
  (circle (- 9 (* n 2)) 360)
  (end_fill)
  (penup)

)
(define (tear-maker n)
  (if (= n 1) (tear 1) (begin (tear n) (tear-maker (- n 1))))
)
(define (face)
  (color "black")
  (right 90)
  (forward 100)
  (left 90)
  (pendown)
  (begin_fill)
  (circle 80 360)
  (color "yellow")
  (end_fill)
  (penup)
  (forward 5)
  (left 90)
  (forward 30)
  (right 90)
  (eye)
  (left 90)
  (forward 12.5)
  (left 90)
  (forward 15)
  (tear-maker 3)
  (backward 60)
  (right 90)
  (forward 67.5)
  (right 90)
  (eye)
  (left 90)
  (forward 24)
  (left 90)
  (forward 24)
  (pendown)
  (begin_fill)
  (color "black")
  (left 90)
  (circle 10 360)
  (end_fill)
  (penup)
  (forward 80)
  (pendown)
  (begin_fill)
  (color "black")
  (circle 10 360)
  (end_fill)
  (penup)
)
(define (face-maker n)
  ( if (= n 1) (begin (face) (penup))(begin (face) (right 45) (forward 700) (face-maker (- n 1)))
)
)
(define (draw)
  (left 90)
  (forward 50)
  (right 90)
  (bgcolor "blue")
  (heart-maker 33)
  (left 90)
  (backward 80)
  (left 90)
  (forward 150)
  (right 150)
  (begin_fill)
  (heart)
  (color "red")
  (end_fill)
  (penup)
  (right 130)
  (forward 150)
  (face)
  (forward 120)
  (right 90)
  (forward 400)
  (face-maker 4)
  (exitonclick))

; Please leave this last line alone.  You may add additional procedures above
; this line.
(draw)